# Generated by Django 5.2.8 on 2025-11-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draw',
            options={'verbose_name': '로또 당첨번호', 'verbose_name_plural': '로또 당첨번호'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': '로또 티켓', 'verbose_name_plural': '로또 티켓'},
        ),
        migrations.RemoveField(
            model_name='draw',
            name='draw_date',
        ),
    ]
