# Generated by Django 5.2.8 on 2025-11-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0002_alter_draw_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='numbers',
            field=models.CharField(max_length=100, verbose_name='당첨 번호'),
        ),
    ]
