# Generated by Django 5.2.8 on 2025-11-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0003_alter_draw_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draw',
            options={'ordering': ['-drawn_at'], 'verbose_name': '로또 당첨번호', 'verbose_name_plural': '로또 당첨번호'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': '로또 티켓', 'verbose_name_plural': '로또 티켓'},
        ),
        migrations.AddField(
            model_name='draw',
            name='bonus_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='보너스 번호'),
        ),
        migrations.AddField(
            model_name='draw',
            name='drawn_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='추첨일시'),
        ),
        migrations.AddField(
            model_name='draw',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='draw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='lotto.draw'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='winning_grade',
            field=models.IntegerField(choices=[(0, '낙첨'), (1, '1등'), (2, '2등'), (3, '3등'), (4, '4등'), (5, '5등')], default=0, verbose_name='당첨 등급'),
        ),
    ]
